default:
  image: ruby:3.2
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/ruby

create-pages:
  stage: deploy
  script:
    - bundle config set --local path vendor
    - bundle install --jobs 4
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  pages: true # publishes the public/ directory as GitLab Pages
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
